query allWebsites {
  allWebsites {
    _id
    name
    description
    url
    ftp {
      host
      user
      password
      directory
    }
    enabledModules
    fields {
      name
      value
    }
  }
}
